pipeline{
  agent any
  
  tools {nodejs "node"}
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('install modules'){
      steps{
        sh '''
          npm install --verbose -d 
        '''
      }
    }
    stage ('build') {
      steps{
        sh '''
        $(npm bin)/ng build --prod --build-optimizer
        npm version patch
        '''
      }
    }
  }
}
